## manages the pods, we talk with this controller and the controler talks with the pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
  labels:
    app: java-app
spec:
  replicas: 1 # how much pods to manage 
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
       - name: java-app
         image: 1631995/java_app5:latest
      volumes:
        - name: app-conf 
          configMap:

           name: app-conf
 
           items:
           - key: "app.conf"
             path: "app.conf"
      
